[plugins]
  [plugins.cri.containerd]
    snapshotter = "overlayfs"
    [plugin.cri.containerd.default_runtime]
      runtime_type = "io.containerd.runtime.v1.linux"
      runtime_engine = "/usr/local/bin/runc"
      runtime_root = ""